[project]
name = "RU_MADS-exam-25"
version = "0.1.0"
description = "Code for MADS deep learning exam"
authors = [
    {name = "Ruben Goedings", email = "ruben.goedings@student.hu.nl"},
]
dependencies = [
    "mads-datasets>=0.3.10",
    "seaborn>=0.13.1",
    "ConfigSpace>=0.7.1",
    "torch-tb-profiler>=0.4.3",
    "tensorboard>=2.16.2",
    "mlflow>=2.13.2",
    "mltrainer>=0.1.129",
    "hyperopt>=0.2.7",
    "torch>=2.5.1",
    "torchinfo>=1.8.0",
    "jrnl>=4.2",
    "imblearn>=0.0",
    "bayesian-optimization>=2.0.3",
    "scikit-optimize>=0.10.2",
]
requires-python = ">=3.11,<3.12"
readme = "README.md"
license = {text = "MIT"}

[dependency-groups]
dev = [
    "isort>=5.13.2",
    "jupyter>=1.1.1",
    "mypy>=1.14.1",
    "pyright>=1.1.391",
    "ruff>=0.9.1",
]

[tool.rye]
managed = true
dev-dependencies = [
    "isort>=5.13.2",
    "jupyter>=1.1.1",
    "pyright>=1.1.391",
    "ruff>=0.9.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/"]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
